version: "3.9"
services:
  auth:
    build:
      context: "."
      dockerfile: "docker/golang/Dockerfile"
      args:
        TARGET: "auth"
    ports: [ "8081:8081" ]
    environment:
      AUTH_ADDR: :8081
      AUTH_HOST_NAME: http://localhost:8081
      AUTH_ISSUER: localhost
      AUTH_AUDIENCE: "*.weberc2.com"
      AUTH_NOTIFICATION_SENDER: auth@weberc2.com
      AUTH_DEFAULT_REDIRECT_LOCATION: http://localhost:8080/posts/foo/comments/__toplevel__/replies
      AUTH_REDIRECT_DOMAIN: "localhost:8080"
      AUTH_BASE_URL: http://localhost:8081
      AWS_REGION: us-east-2
      PG_PASS: password
      PG_HOST: postgres

      # Secrets
      AUTH_CODE_SIGNING_KEY: "${AUTH_CODE_SIGNING_KEY}"
      AUTH_ACCESS_SIGNING_KEY: "${AUTH_ACCESS_SIGNING_KEY}"
      AUTH_REFRESH_SIGNING_KEY: "${AUTH_REFRESH_SIGNING_KEY}"
      AUTH_RESET_SIGNING_KEY: "${AUTH_RESET_SIGNING_KEY}"
      AWS_ACCESS_KEY_ID: "${AUTH_AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AUTH_AWS_SECRET_ACCESS_KEY}"

  postgres:
    image: "postgres:14"
    ports: [ "5432:5432" ]
    environment:
      POSTGRES_PASSWORD: password

  comments:
    build:
      context: "."
      dockerfile: "docker/golang/Dockerfile"
      args:
        TARGET: "comments"
    ports: [ "8080:8080" ]
    environment:
      ADDR: ":8080"
      LOGIN_URL: http://localhost:8081/login
      REGISTER_URL: http://localhost:8081/register
      PASSWORD_RESET_URL: http://localhost:8081/password/reset
      BASE_URL: http://localhost:8080
      AUTH_BASE_URL: http://auth:8081
      BUCKET: weberc2-comments
      ACCESS_KEY: "${COMMENTS_ACCESS_PUBLIC_KEY}"
      AWS_REGION: us-east-2
      COOKIE_ENCRYPTION_KEY: test-key
      PG_PASS: password
      PG_HOST: postgres

      # Secrets
      AWS_ACCESS_KEY_ID: "${COMMENTS_AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${COMMENTS_AWS_SECRET_ACCESS_KEY}"
