apiVersion: v1
kind: Service
metadata:
  namespace: serverstatus
  name: serverstatus
  labels:
    app: serverstatus
spec:
  type: ClusterIP
  selector:
    app: serverstatus
  ports:
    - name: http
      targetPort: 8080
      port: 80
      protocol: TCP
